// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jQevD6uNN2KB_I9Zzt2A7LZa76V9_iI',
    appId: '1:534980312634:android:11c0691f706a4a3dfc3f03',
    messagingSenderId: '534980312634',
    projectId: 'goatlas-database-moblieapp-kku',
    databaseURL: 'https://goatlas-database-moblieapp-kku-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'goatlas-database-moblieapp-kku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvv-AaMvJ4-VXEjt5wbpA6vIhkRIhlr4',
    appId: '1:534980312634:ios:e2ad5eb7f60c9275fc3f03',
    messagingSenderId: '534980312634',
    projectId: 'goatlas-database-moblieapp-kku',
    databaseURL: 'https://goatlas-database-moblieapp-kku-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'goatlas-database-moblieapp-kku.firebasestorage.app',
    iosBundleId: 'com.example.goatlas',
  );

}